- name: Install MySQL Server
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Copy configuration file
  copy: src=my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify:
  - restart mysql

- name: Update MySQL root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql.admin_password }} priv=*.*:ALL,GRANT state=present
  with_items:
    - {{ mysql.bind }}
    - 127.0.0.1
    - ::1
    - localhost