- name: Install MySQL Server
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - python-mysqldb

- name: Copy configuration file
  copy: src=files/my.cnf dest=/etc/my.cnf owner=root group=root mode=0644
  notify:
  - restart mysql